"""
Structured regression report output.

Supports JSON, Markdown, and HTML export for CI/CD integration.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Literal, Union

from .benchmark.scorer import GeneralizationReport, RegressionAlert

Format = Literal["json", "markdown", "html"]


def _score_bar(score: float, width: int = 20) -> str:
    filled = int(score * width)
    return "█" * filled + "░" * (width - filled)


def _render_markdown(report: GeneralizationReport, alert: RegressionAlert | None = None) -> str:
    lines = [
        "# retrieval-guard Report",
        "",
        f"**Model:** `{report.model_name}`",
        f"**Overall Generalization Score:** {report.overall_score:.1%}  `{_score_bar(report.overall_score)}`",
        f"**Pairs Tested:** {report.total_pairs}  |  **Passed:** {report.passed_pairs}  |  **Failed:** {report.total_pairs - report.passed_pairs}",
        "",
        "## Per-Category Breakdown",
        "",
        "| Category | Score | Bar |",
        "|----------|-------|-----|",
    ]
    for cat, score in report.per_category.items():
        lines.append(f"| {cat} | {score:.1%} | `{_score_bar(score)}` |")

    if report.failure_ids:
        lines += ["", "## Failed Test IDs", "", ", ".join(f"`{fid}`" for fid in report.failure_ids)]

    if alert:
        lines += [
            "",
            "## Regression Check",
            "",
            f"**Alert Fired:** {'🔴 YES' if alert.fired else '🟢 NO'}",
            f"**Delta:** {alert.delta:+.1%}  (threshold: {alert.threshold:.1%})",
            f"**Before:** {alert.before_score:.1%}  →  **After:** {alert.after_score:.1%}",
        ]
        if alert.new_failures:
            lines.append(f"**New Failures:** {', '.join(f'`{f}`' for f in alert.new_failures)}")
        lines += ["", f"> {alert.recommendation}"]

    lines += ["", "---", "_Generated by [retrieval-guard](https://github.com/your-org/retrieval-guard)_"]
    return "\n".join(lines)


def _render_html(report: GeneralizationReport, alert: RegressionAlert | None = None) -> str:
    alert_block = ""
    if alert:
        color = "#d32f2f" if alert.fired else "#388e3c"
        alert_block = f"""
        <div style="margin-top:24px;padding:16px;border-left:4px solid {color};background:#fafafa;">
          <h3 style="margin:0 0 8px 0;color:{color};">Regression Check — {'ALERT FIRED' if alert.fired else 'PASS'}</h3>
          <table style="border-collapse:collapse;">
            <tr><td><b>Delta</b></td><td style="padding-left:16px">{alert.delta:+.1%}</td></tr>
            <tr><td><b>Threshold</b></td><td style="padding-left:16px">{alert.threshold:.1%}</td></tr>
            <tr><td><b>Before</b></td><td style="padding-left:16px">{alert.before_score:.1%}</td></tr>
            <tr><td><b>After</b></td><td style="padding-left:16px">{alert.after_score:.1%}</td></tr>
          </table>
          <p style="margin:12px 0 0 0;color:#333;">{alert.recommendation}</p>
        </div>"""

    category_rows = "".join(
        f"<tr><td>{cat}</td><td>{score:.1%}</td></tr>"
        for cat, score in report.per_category.items()
    )

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>retrieval-guard Report</title>
<style>
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:700px;margin:40px auto;color:#222;}}
  h1{{color:#0a2a2a;}} table{{border-collapse:collapse;width:100%;}}
  td,th{{border:1px solid #ddd;padding:8px 12px;}} th{{background:#0a2a2a;color:#fff;}}
  .score{{font-size:2em;font-weight:700;color:#1a4a3a;}}
</style>
</head>
<body>
<h1>retrieval-guard Report</h1>
<p><b>Model:</b> <code>{report.model_name}</code></p>
<p class="score">{report.overall_score:.1%}</p>
<p><b>Pairs:</b> {report.total_pairs} tested / {report.passed_pairs} passed / {report.total_pairs - report.passed_pairs} failed</p>
<h2>Per-Category Breakdown</h2>
<table><tr><th>Category</th><th>Score</th></tr>{category_rows}</table>
{alert_block}
<p style="margin-top:32px;color:#888;font-size:12px;">Generated by retrieval-guard</p>
</body>
</html>"""


def export(
    report: GeneralizationReport,
    alert: RegressionAlert | None = None,
    format: Format = "json",
    path: Union[str, Path, None] = None,
) -> str:
    """
    Export a GeneralizationReport (and optional RegressionAlert) as a structured document.

    Args:
        report: The GeneralizationReport to export.
        alert: Optional RegressionAlert to include in the report.
        format: "json" | "markdown" | "html"
        path: Optional file path to write to. If None, returns the string.

    Returns:
        The rendered report string (also writes to `path` if provided).
    """
    if format == "json":
        data = report.to_dict()
        if alert:
            data["regression_alert"] = alert.to_dict()
        content = json.dumps(data, indent=2)
    elif format == "markdown":
        content = _render_markdown(report, alert)
    elif format == "html":
        content = _render_html(report, alert)
    else:
        raise ValueError(f"Unknown format: {format!r}. Must be 'json', 'markdown', or 'html'.")

    if path is not None:
        Path(path).write_text(content, encoding="utf-8")

    return content
